### ISSUE TITLE
initialise authority list based off app props

### ISSUE THREAD

**Issue by joshuavial** [joshuavial/bridge.hc#1]

**Comment by joshuavial** [comment]
chicken and egg problem knowing the authority keys
using init callback to add progenitor to the authority list to bootstrap network

**Comment by joshuavial** [comment]
@nick-stebbings I did a little more on this and pushed to wip https://github.com/joshuavial/bridge.hc/commit/3a72324cb6b5c3a5ac6aec8deb75f572c52da4b5 

Main idea is to query the progenitors chain to find the create authority list action hash so agents can use that to find the current authorities. Still a fair bit to do

**Comment by nick-stebbings** [comment]
@joshuavial ok, that makes sense. My brain is still in lacking-sleep mush so I will join again tomorrow.

**Comment by joshuavial** [comment]
hooray - we've shipped one

**Comment by nick-stebbings** [comment]
Nice!
